language:
  elixir

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.4
    - otp_release: 20.1
      elixir: 1.6.1

script:
  - if [[ `elixir -v` = *"1.6"* ]]; then mix format --check-formatted; fi
  - mix test

sudo:
  false
