language:
  elixir
elixir:
  - 1.0.2
otp_release:
  - 17.4
sudo:
  false # to use faster container based build environment
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - andrea@leopardi.me
