name: Publish to Hex

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  publish:
    name: Publish to Hex

    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Erlang and Elixir
        uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        with:
          otp-version: "27.2"
          elixir-version: "1.18"

      - name: Fetch dependencies
        run: mix deps.get

      - name: Publish to Hex
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
